ERROR    - 2023-08-09 20:01:17,252. В файле "__main__", записала сообщение: Функция с именем task_1, имея аргументы [2, 0] выдает результат division by zero
